[package]
name = 'jsdotlua/jest-reporters'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.4.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.1'
JestConsole = 'jsdotlua/jest-console@3.4.1'
JestMock = 'jsdotlua/jest-mock@3.4.1'
JestTestResult = 'jsdotlua/jest-test-result@3.4.1'
JestTypes = 'jsdotlua/jest-types@3.4.1'
JestUtil = 'jsdotlua/jest-util@3.4.1'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
Path = 'jsdotlua/path@3.4.1'
RobloxShared = 'jsdotlua/roblox-shared@3.4.1'
TestUtils = 'jsdotlua/test-utils@3.4.1'
