[tools]
rojo = "UpliftGames/rojo@7.3.0-uplift.11"
wally = "grilme99/wally@0.4.0"
stylua = "johnnymorganz/stylua@0.18.1"
luau-lsp = "johnnymorganz/luau-lsp@1.23.0"
selene = "Kampfkarren/selene@0.25.0"
wally-package-types = "johnnymorganz/wally-package-types@1.2.1"
