std = "roblox"

[lints]
# _G is used for global development feature flags
global_usage = "allow"
empty_if = "allow"
shadowing = "allow"
if_same_then_else = "allow"

# TODO: Actually fix unused varaibles. This is just a bandaid.
unused_variable = "allow"
