[package]
name = 'jsdotlua/jest-runner'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.0'
Emittery = 'jsdotlua/emittery@3.2.5'
JestCircus = 'jsdotlua/jest-circus@3.2.5'
JestConsole = 'jsdotlua/jest-console@3.2.5'
JestEnvironment = 'jsdotlua/jest-environment@3.2.5'
JestMessageUtil = 'jsdotlua/jest-message-util@3.2.5'
JestRuntime = 'jsdotlua/jest-runtime@3.2.5'
JestTestResult = 'jsdotlua/jest-test-result@3.2.5'
JestTypes = 'jsdotlua/jest-types@3.2.5'
JestUtil = 'jsdotlua/jest-util@3.2.5'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
Promise = 'evaera/promise@4.0.0'
RobloxShared = 'jsdotlua/roblox-shared@3.2.5'
Throat = 'jsdotlua/throat@3.2.5'
