[package]
name = 'jsdotlua/roblox-shared'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.4.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
JestGetType = 'jsdotlua/jest-get-type@3.4.1'
JestMock = 'jsdotlua/jest-mock@3.4.1'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
