[package]
name = 'jsdotlua/jest'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.4.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
JestCore = 'jsdotlua/jest-core@3.4.1'
