[package]
name = 'jsdotlua/jest-message-util'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.4.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.1'
JestTypes = 'jsdotlua/jest-types@3.4.1'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
PrettyFormat = 'jsdotlua/pretty-format@3.4.1'
RegExp = 'jsdotlua/regex@1.0.2'
RobloxShared = 'jsdotlua/roblox-shared@3.4.1'
