[package]
name = 'jsdotlua/jest-environment'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
JestFakeTimers = 'jsdotlua/jest-fake-timers@3.2.5'
JestMock = 'jsdotlua/jest-mock@3.2.5'
JestTypes = 'jsdotlua/jest-types@3.2.5'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
