[package]
name = 'jsdotlua/jest-diff'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT + Apache 2.0'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'core-packages/chalk-lua@0.2.0'
DiffSequences = 'core-packages/diff-sequences@3.2.5'
JestGetType = 'core-packages/jest-get-type@3.2.5'
JestTypes = 'core-packages/jest-types@3.2.5'
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
PrettyFormat = 'core-packages/pretty-format@3.2.5'
