[package]
name = 'jsdotlua/jest-diff'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.4.1'
license = 'MIT + Apache 2.0'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.1'
DiffSequences = 'jsdotlua/diff-sequences@3.4.1'
JestGetType = 'jsdotlua/jest-get-type@3.4.1'
JestTypes = 'jsdotlua/jest-types@3.4.1'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
PrettyFormat = 'jsdotlua/pretty-format@3.4.1'
