[package]
name = 'jsdotlua/expect'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
JestGetType = 'core-packages/jest-get-type@3.2.5'
JestMatcherUtils = 'core-packages/jest-matcher-utils@3.2.5'
JestMessageUtil = 'core-packages/jest-message-util@3.2.5'
JestSnapshot = 'core-packages/jest-snapshot@3.2.5'
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
Promise = 'evaera/promise@4.0.0'
RegExp = 'jsdotlua/regex@1.0.0'
RobloxShared = 'core-packages/roblox-shared@3.2.5'
