[package]
name = 'jsdotlua/jest-config'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.4.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.1'
JestEnvironmentLuau = 'jsdotlua/jest-environment-luau@3.4.1'
JestGetType = 'jsdotlua/jest-get-type@3.4.1'
JestTypes = 'jsdotlua/jest-types@3.4.1'
JestUtil = 'jsdotlua/jest-util@3.4.1'
JestValidate = 'jsdotlua/jest-validate@3.4.1'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
Promise = 'evaera/promise@4.0.0'
RegExp = 'jsdotlua/regex@1.0.2'
RobloxShared = 'jsdotlua/roblox-shared@3.4.1'
