[package]
name = 'jsdotlua/test-utils'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.0'
JestEnvironmentLuau = 'jsdotlua/jest-environment-luau@3.2.5'
JestTypes = 'jsdotlua/jest-types@3.2.5'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
PrettyFormat = 'jsdotlua/pretty-format@3.2.5'
