[package]
name = 'jsdotlua/jest-matcher-utils'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.0'
JestDiff = 'jsdotlua/jest-diff@3.2.5'
JestGetType = 'jsdotlua/jest-get-type@3.2.5'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
PrettyFormat = 'jsdotlua/pretty-format@3.2.5'
RegExp = 'jsdotlua/regex@1.0.0'
