[package]
name = 'jsdotlua/jest-get-type'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
RegExp = 'jsdotlua/regex@1.0.0'
