[package]
name = 'jsdotlua/jest-core'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'core-packages/chalk-lua@0.2.0'
Emittery = 'core-packages/emittery@3.2.5'
JestConfig = 'core-packages/jest-config@3.2.5'
JestConsole = 'core-packages/jest-console@3.2.5'
JestMessageUtil = 'core-packages/jest-message-util@3.2.5'
JestReporters = 'core-packages/jest-reporters@3.2.5'
JestRunner = 'core-packages/jest-runner@3.2.5'
JestRuntime = 'core-packages/jest-runtime@3.2.5'
JestSnapshot = 'core-packages/jest-snapshot@3.2.5'
JestTestResult = 'core-packages/jest-test-result@3.2.5'
JestTypes = 'core-packages/jest-types@3.2.5'
JestUtil = 'core-packages/jest-util@3.2.5'
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
PrettyFormat = 'core-packages/pretty-format@3.2.5'
Promise = 'evaera/promise@4.0.0'
RegExp = 'jsdotlua/regex@1.0.0'
RobloxShared = 'core-packages/roblox-shared@3.2.5'
