[package]
name = 'jsdotlua/jest-core'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.4.1'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ChalkLua = 'jsdotlua/chalk-lua@0.2.1'
Emittery = 'jsdotlua/emittery@3.4.1'
JestConfig = 'jsdotlua/jest-config@3.4.1'
JestConsole = 'jsdotlua/jest-console@3.4.1'
JestMessageUtil = 'jsdotlua/jest-message-util@3.4.1'
JestReporters = 'jsdotlua/jest-reporters@3.4.1'
JestRunner = 'jsdotlua/jest-runner@3.4.1'
JestRuntime = 'jsdotlua/jest-runtime@3.4.1'
JestSnapshot = 'jsdotlua/jest-snapshot@3.4.1'
JestTestResult = 'jsdotlua/jest-test-result@3.4.1'
JestTypes = 'jsdotlua/jest-types@3.4.1'
JestUtil = 'jsdotlua/jest-util@3.4.1'
LuauPolyfill = 'jsdotlua/luau-polyfill@1.2.3'
PrettyFormat = 'jsdotlua/pretty-format@3.4.1'
Promise = 'evaera/promise@4.0.0'
RegExp = 'jsdotlua/regex@1.0.2'
RobloxShared = 'jsdotlua/roblox-shared@3.4.1'
