[package]
name = 'jsdotlua/jest-environment-luau'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
JestEnvironment = 'core-packages/jest-environment@3.2.5'
JestFakeTimers = 'core-packages/jest-fake-timers@3.2.5'
JestMock = 'core-packages/jest-mock@3.2.5'
JestTypes = 'core-packages/jest-types@3.2.5'
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
Promise = 'evaera/promise@4.0.0'
