[package]
name = 'jsdotlua/jest-fake-timers'
description = 'https://github.com/jsdotlua/jest-lua'
version = '3.2.5'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
JestGetType = 'core-packages/jest-get-type@3.2.5'
JestMock = 'core-packages/jest-mock@3.2.5'
LuauPolyfill = 'core-packages/luau-polyfill@1.2.3'
